name: surya
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  flutter_screenutil: ^5.0.0+2
  pin_code_fields: ^7.2.0
  flutter_svg: ^0.22.0
  http: ^0.13.3
  logger: ^1.0.0
  flutter_dotenv: ^5.0.0
  socket_io_client: ^1.0.1
  photo_view: ^0.11.1
  intl: ^0.17.0
  rsa_encrypt: ^2.0.0
  encrypt: ^5.0.0
  image_picker: ^0.8.1+3
  image_cropper: ^1.4.1
  device_info: ^2.0.2
  convert: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  connectivity: ^3.0.6
  file_picker: ^3.0.3
  share: ^2.0.4
  open_file: ^3.2.1
  swipe_to: ^0.1.0-nullsafety.1
  flutter_image_compress: ^1.0.0
  flutter_webrtc: ^0.6.5
  webview_flutter: ^2.0.9
  clipboard: ^0.1.3
  upgrader: ^3.3.1
  new_version: ^0.2.2
  contacts_service: ^0.6.1
  passcode_screen: ^2.0.0
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  get_storage: ^2.0.1
  path_provider: ^2.0.2
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_secure_storage: ^4.2.0
  url_launcher: ^6.0.9
  permission_handler: ^8.1.4+2
  emoji_picker_flutter: ^1.0.6
  infinite_scroll_pagination: ^3.1.0

  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - .env

  fonts:
    - family: Helvetica Neue Ultra Light
      fonts:
        - asset: assets/fonts/Helvetica.ttf
