name: surya
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  flutter_screenutil: ^5.0.0+2
  pin_code_fields: ^7.2.0
  flutter_svg: ^0.22.0
  http: ^0.13.3
  logger: ^1.0.0
  connectivity: ^3.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Helvetica Neue Ultra Light
      fonts:
        - asset: assets/fonts/Lowvetica.ttf
